# Generated by Django 5.2.1 on 2025-06-19 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('domain', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.city')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.city')),
                ('id_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.district')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('id_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthdate', models.DateField(db_index=True)),
                ('cellphone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('p_surname', models.CharField(max_length=15)),
                ('m_surname', models.CharField(max_length=15)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.department')),
                ('id_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('p_surname', models.CharField(db_index=True, max_length=15)),
                ('m_surname', models.CharField(db_index=True, max_length=15)),
                ('document', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=15)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.typedocument')),
            ],
        ),
    ]
